# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - prefer_single_quotes
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - unawaited_futures
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_print
